#!/usr/bin/env python3
"""Generate firmware/components/audio_alert/beep_pcm.h.

Run once locally; commit the produced header. 200 ms 1 kHz sine wave at
16 kHz / 16-bit signed mono.

  python scripts/gen_beep.py > firmware/components/audio_alert/beep_pcm.h
"""
import math

SR, FREQ, MS, AMP = 16000, 1000, 200, 18000
n = SR * MS // 1000
samples = [int(AMP * math.sin(2 * math.pi * FREQ * i / SR)) for i in range(n)]

print('// auto-generated by scripts/gen_beep.py — do not edit by hand')
print('#pragma once')
print('#include <stdint.h>')
print(f'#define BEEP_PCM_SAMPLES {n}')
print(f'#define BEEP_PCM_SAMPLE_RATE {SR}')
print('static const int16_t BEEP_PCM[BEEP_PCM_SAMPLES] = {')
for i in range(0, n, 12):
    print('  ' + ', '.join(str(s) for s in samples[i:i+12]) + ',')
print('};')
